version: '3'

services:
  app:
    restart: always
    env_file: .env
    command: ${START_COMMAND}
    build: ./
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=$NODE_ENV
      - PORT=$PORT
      - HOST=$HOST
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - ${NGINX_PROXY_PORT}:${NGINX_PROXY_PORT}
    depends_on:
      - app

volumes:
  database: